name: Deploy-1
# on: push
on: 
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      # use dependencies caching
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm #folder to cache
          key: deps-node-module-${{ hashFile('**/package-lock.json') }}
      #- name: Install NodeJS
      #  uses: actions/setup-node@v4
      #  with:
      #    node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Lint code
        run: npm run lint
      - name: Test code
        run: npm run test
  build:
    runs-on: ubuntu-latest
    needs: test
    # output related to 'Publish JS filename' step
    outputs:
      file-name: ${{ steps.publish.outputs.script-file }}
    steps:
      - name: Get code
        uses: actions/checkout@v4
      #- name: Install NodeJS
      #  uses: actions/setup-node@v4
      #  with:
      #    node-version: 18
      # use dependencies caching
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm #folder to cache
          key: deps-node-module-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Make build
        run: npm run build
      - name: Publish JS filename
        id: publish
        run: find dist/assets/*.js -type f -execdir echo 'script-file={}' >> $GITHUB_OUTPUT ';'
      # job artifact upload
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: dist
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # job artifact download
      - name: Get build artifacts
        uses: actions/download-artifact@v4
        with: 
          name: build-artifact
      - name: Print files name
        run: ls
      # use publish output
      - name: Print publish output
        run: echo "${{ needs.build.outputs.file-name }}"
      - name: Make deploy
        run: echo "Deploying..."