name: Show issue details
# on: issues
on:
  issues:
    types: opened
jobs:
  get_issue_detail:
    runs-on: ubuntu-latest
    steps:
      - name: Get issue details
        run: echo "${{ toJSON(github.event) }}"
